In [1]:
import numpy as np

In [2]:
y	Wy,1	Wy,2
A	-0.89	-1.77
B	1.38	-0.21
C	-1.47	0.37




SyntaxError: invalid syntax (<ipython-input-2-49efd79359b3>, line 1)

In [90]:
x1 = np.array([-.59,-1.06])
y1 = 2

LABELS = {0:"A",1:"B",2:"C"}


In [72]:
w = np.array([[-0.89,-1.77],[1.38,-0.21],[-1.47,0.37]])

In [73]:
x,y

(array([-0.59, -1.06]), 2)

In [74]:
w

array([[-0.89, -1.77],
       [ 1.38, -0.21],
       [-1.47,  0.37]])

In [75]:
def performUpdate(w,x,y):
    scores = w.dot(x)
    top_score = np.argmax(scores)
    correct_label = y
    w_new = w.copy()
    if (top_score == correct_label):
        return scores, w_new
    w_new[top_score] = w_new[top_score] - x
    w_new[correct_label] = w_new[correct_label] + x
    return scores, w_new
scores, w_run1 = performUpdate(w,x1,y1)

In [76]:
scores, w_run1

(array([ 2.4013, -0.5916,  0.4751]), array([[-0.3 , -0.71],
        [ 1.38, -0.21],
        [-2.06, -0.69]]))

In [77]:
x2 = np.array([-.5,0.63]) 
y2 = 2
scores, w_run2 = performUpdate(w_run1,x2,y2)

In [78]:
y	Wy,1	Wy,2
A	2.62	0.12
B	2.56	-1.09
C	-6.16	-0.64
scores, w_run2

(array([-0.2973, -0.8223,  0.5953]), array([[-0.3 , -0.71],
        [ 1.38, -0.21],
        [-2.06, -0.69]]))

In [84]:
w_final = np.array([[2.62,0.12],[2.56,-1.09],[-6.16,-0.64]])
q = np.array([.44,1.46])
scores = w_final.dot(q)

In [85]:
w_final

array([[ 2.62,  0.12],
       [ 2.56, -1.09],
       [-6.16, -0.64]])

In [86]:
q

array([ 0.44,  1.46])

In [92]:
label = np.argmax(scores)
predicted_label = LABELS[label]
predicted_label

'A'